### ISSUE TITLE
TSLint coding style warnings

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-dummies#2]
Hello @makimenko,

thank you very much for the Three.js template! I would like to contribute some minor features I added back to this repository, but I will resort these to individual PRs.
Apart from that, would you accept a PR with style changes only, fixing all the warnings issued by TSLint (with the options from [Angular](https://github.com/makimenko/angular-template-for-dummies/blob/master/tslint.json))?  For example, usage of `'` instead of `"`, omission of types for trivially inferrable declarations (`const x: number = 5` -> `const x = 5`).

**Comment by ComFreek** [comment]
That's nice to hear! See PRs #3 and #4. I will wait for them to be merged and/or commented at by you before adding a feature PR based on their Git history.

I am looking forward to hearing back from you :smile:
Best Regards,

**Comment by makimenko** [comment]
Thanks for contribution and valuable comments RE:
- angular-seed
- naming of the directives
will think about it ....

Both Pull Requests merged.

Have a nice day and Best Regards,
