### ISSUE TITLE
Project description still contains old Angular v5

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-dummies#6]
This is just a really minor nitpicking comment:
```
Several templates for Angular 5 projects with frequently used technology stacks
```

Now that #3 upgraded the project (at least master and threejs) to Angular 6.0.0, I think the project description should be changed accordingly.

**Comment by makimenko** [comment]
Fixed.
Thanks for PR with upgrade to 6.0.0.. 
Currently checking new features, looks very promising (especially support for libraries and multiple applications)

**Comment by ComFreek** [comment]
Leave a comment
